#!/bin/bash
# Run LLVM-related Rust tests
# Tests both ori_llvm and ori_rt crates
#
# Usage: ./llvm-test [additional args...]
#
# Note: Requires LLVM 17 installed. Path configured in .cargo/config.toml

cargo test -p ori_llvm -p ori_rt "$@"
